#
# This file contains configuration flags to customize your site
#

defaults:
  -
    scope:
      path: "_pages" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "single"

minimal_mistakes_skin : "default" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Italiano Lab"
title_separator          : "-"
subtitle                 : "Software Development & Architectural Engineering Labs"
name                     : &name "Ing. Salvatore Maria" # &name is a YAML anchor which can be *referenced later
description: Software Development & Engineering Lab # Short bio or description (displayed in the header)

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://www.ducatodipiazzapontida.it/media/images/articles/I.png

github:
  zip_url: https://github.com/Astr0surf3r/italianolab/archive/refs/heads/master.zip
  tar_url: https://github.com/parsiad/mlinterp/archive/v0.1.zip
  repository_url: https://github.com/Astr0surf3r/italianolab

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: https://github.com/Astr0surf3r/italianolab
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-1CC5T1VYWX

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: #""

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: #"https://kepasa-project.github.io/k-blog"

#
# !! You don't need to change any of the configuration flags below !!
#
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-font-awesome-sass
  - jekyll-include-cache

font-awesome:
  assets: true

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# jekyll theme
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "https://avatars.githubusercontent.com/u/896968?v=4"
  bio              : "Passion for Development and Architectural Design"
  location         : "America, Europe"
  links:
    - label: "ItalianoLab Source Code"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/Astr0surf3r/italianolab"
    - label: "Telegram"
      icon: "fab fa-telegram-plane"
      url: "https://t.me/astr0surf3r"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Astr0surf3r/italianolab"

# Reading Files
include:
  - .htaccess
  - _pages

plugins:
  - jekyll-include-cache
  